Entrega para revisión del TP Integrador
Desarrollo-de-Software-2024-Gadea/App-BE pull request #31
Opened 2024-12-03 20:25 UTC by TaniJG

2024-12-09 23:28 UTC, enzoftv requested changes

2024-12-09 23:28 UTC, enzoftv commented on SerializedStalker/SerializedStalker/src/SerializedStalker.Application/Notificaciones/NotificacionService.cs
> +            // Crear un DTO para la notificación
deberian incorporar loggers en cada parte importante del código

2024-12-09 23:28 UTC, enzoftv commented on SerializedStalker/SerializedStalker/src/SerializedStalker.Application/Notificaciones/NotificadorPantalla.cs
> +        // Lógica para mostrar la notificación en pantalla
Como funcionaria este notificador?

2024-12-09 23:28 UTC, enzoftv commented on SerializedStalker/SerializedStalker/src/SerializedStalker.Application/Workers/SerieUpdateChecker.cs
> +    public class SerieUpdateChecker : IHostedService, IDisposable
Porque usaron un IHostedService y no un AsyncBackgroundJob o BackgroundWorkerBase?

2024-12-09 23:28 UTC, enzoftv commented on SerializedStalker/SerializedStalker/src/SerializedStalker.Application/Notificaciones/NotificadorEmail.cs
> +            // Lógica para enviar un correo electrónico usando notificacion.Titulo y notificacion.Mensaje
Falta la lógica de envío de mail.

2024-12-09 23:28 UTC, enzoftv commented on SerializedStalker/src/SerializedStalker.Application/Series/SerieAppService.cs
> +                monitoreo.HoraSalida = DateTime.Now;
Tiene  código duplicado en la determinación de los tiempos. La entidad que establece los tiempos debería ser una entidad, servicio o helper. Con sus test unitarios.

2024-12-09 23:28 UTC, enzoftv commented on SerializedStalker/src/SerializedStalker.Application/Series/SerieAppService.cs
> +                var seriesExistentes = await _serieRepository.GetListAsync();
Este codigo es muy extenso y de baja abstracción. Deberia estar en un DomainManager o similar.

2024-12-10 00:22 UTC, TaniJG commented on SerializedStalker/SerializedStalker/src/SerializedStalker.Application/Notificaciones/NotificacionService.cs
> +            // Crear un DTO para la notificación
Esta corrección no la entiendo, en NotificacionService hay loggers

2024-12-16 21:56 UTC, closed without merging